# Generated by Django 5.0 on 2026-01-28 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("INFANT", "Infant Room (0-12 months)"),
                            ("TODDLER", "Toddler Room (1-2 years)"),
                            ("PRESCHOOL", "Preschool (3-4 years)"),
                            ("PREKINDERGARTEN", "Pre-K (4-5 years)"),
                            ("MIXED", "Mixed Age"),
                        ],
                        default="MIXED",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=20, help_text="Maximum number of students"
                    ),
                ),
                (
                    "min_age_months",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum age in months"
                    ),
                ),
                (
                    "max_age_months",
                    models.PositiveIntegerField(
                        default=60, help_text="Maximum age in months"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "STAFF"},
                        related_name="assigned_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("theme", models.CharField(blank=True, max_length=200)),
                ("objectives", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date"],
                "unique_together": {("room", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="RoomDeviceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("is_kiosk_mode", models.BooleanField(default=False)),
                ("allow_checkin", models.BooleanField(default=True)),
                ("allow_checkout", models.BooleanField(default=True)),
                ("require_signature", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_mode",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("morning_activity", models.TextField(blank=True)),
                ("afternoon_activity", models.TextField(blank=True)),
                ("learning_goals", models.TextField(blank=True)),
                ("materials_needed", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to="rooms.lessonplan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily Activities",
                "ordering": ["date"],
                "unique_together": {("lesson_plan", "date")},
            },
        ),
    ]
