# Generated by Django 5.0 on 2026-01-28 23:16

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=300)),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="school_logos",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address_line_1", models.CharField(max_length=200)),
                ("address_line_2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Profile",
                "verbose_name_plural": "School Profile",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("send_email", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed", "-priority", "remind_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkin_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable/disable check-in kiosk mode"
                    ),
                ),
                (
                    "require_checkin_code",
                    models.BooleanField(
                        default=True, help_text="Require check-in code for kiosk access"
                    ),
                ),
                (
                    "auto_assign_rooms",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically assign students to rooms based on age",
                    ),
                ),
                (
                    "max_students_per_room",
                    models.PositiveIntegerField(
                        default=20, help_text="Maximum students per room"
                    ),
                ),
                (
                    "learning_framework",
                    models.CharField(
                        default="Montessori",
                        help_text="Primary learning framework (e.g., Montessori, Reggio Emilia)",
                        max_length=100,
                    ),
                ),
                (
                    "parents_can_edit_student_info",
                    models.BooleanField(
                        default=False,
                        help_text="Allow parents to edit their child's information",
                    ),
                ),
                (
                    "parents_can_add_activities",
                    models.BooleanField(
                        default=False,
                        help_text="Allow parents to add activities for their children",
                    ),
                ),
                (
                    "default_activities_to_staff_only",
                    models.BooleanField(
                        default=True,
                        help_text="Show default activities only to staff members",
                    ),
                ),
                (
                    "enable_parent_messaging",
                    models.BooleanField(
                        default=True,
                        help_text="Enable messaging between parents and staff",
                    ),
                ),
                (
                    "enable_staff_messaging",
                    models.BooleanField(
                        default=True, help_text="Enable messaging between staff members"
                    ),
                ),
                (
                    "registration_enabled",
                    models.BooleanField(
                        default=True, help_text="Allow new parent registrations"
                    ),
                ),
                (
                    "registration_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Registration fee amount",
                        max_digits=10,
                    ),
                ),
                (
                    "send_welcome_emails",
                    models.BooleanField(
                        default=True, help_text="Send welcome emails to new users"
                    ),
                ),
                (
                    "send_activity_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Send notifications for important activities",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="school.schoolprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
            },
        ),
    ]
