# Generated by Django 5.0 on 2026-02-05 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("STAFF_SHIFT", "Staff Shift"),
                            ("STUDENT_SCHEDULE", "Student Schedule"),
                            ("ACTIVITY", "Activity Schedule"),
                            ("ROOM_SCHEDULE", "Room Schedule"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("ONCE", "One Time"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="ONCE",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_schedules",
                        to="rooms.room",
                    ),
                ),
                (
                    "assigned_staff",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["STAFF", "ADMIN"]},
                        related_name="attendance_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attendance_schedules",
                        to="students.student",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_in_code_verified", models.BooleanField(default=False)),
                (
                    "is_healthy",
                    models.BooleanField(
                        default=True, help_text="Is the child healthy today?"
                    ),
                ),
                (
                    "health_notes",
                    models.TextField(
                        blank=True, help_text="Additional health notes if needed"
                    ),
                ),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_code_verified", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CHECKED_IN", "Checked In"),
                            ("CHECKED_OUT", "Checked Out"),
                        ],
                        default="CHECKED_IN",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_in_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "check_out_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkouts_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_checkins",
                        to="rooms.room",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkin_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-check_in_time"],
                "indexes": [
                    models.Index(
                        fields=["student", "-date"],
                        name="attendance__student_eec6b9_idx",
                    ),
                    models.Index(
                        fields=["date", "status"], name="attendance__date_db1dc3_idx"
                    ),
                    models.Index(
                        fields=["room", "date"], name="attendance__room_id_448808_idx"
                    ),
                ],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="StaffTimecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("clock_in_time", models.DateTimeField()),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.room",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        limit_choices_to={"role": "STAFF"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_timecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-clock_in_time"],
                "unique_together": {("staff", "date", "clock_in_time")},
            },
        ),
    ]
