# Generated by Django 5.1.15 on 2026-05-27 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancecheckin",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="stafftimecard",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
