# Generated by Django 5.1.15 on 2026-05-23 01:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("students", "0002_vaccinetype_student_additional_details_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("STAFF", "Staff"),
                            ("PARENT", "Parent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("first_arrival", models.TimeField(blank=True, null=True)),
                ("last_departure", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="students.student",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "person_type"],
                        name="time_tracke_date_11b301_idx",
                    )
                ],
                "unique_together": {
                    ("date", "person_type", "student"),
                    ("date", "person_type", "user"),
                },
            },
        ),
        migrations.CreateModel(
            name="TimeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("STAFF", "Staff"),
                            ("PARENT", "Parent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("clock_in", models.DateTimeField(default=django.utils.timezone.now)),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active (On Site)"),
                            ("CLOSED", "Closed (Left)"),
                            ("VOID", "Void (Error / Removed)"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "PARENT"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_sessions_as_parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["STAFF", "ADMIN"]},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_sessions_as_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_checkin",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_session",
                        to="attendance.attendancecheckin",
                    ),
                ),
            ],
            options={
                "ordering": ["-clock_in"],
                "indexes": [
                    models.Index(
                        fields=["date", "status"], name="time_tracke_date_91aafa_idx"
                    ),
                    models.Index(
                        fields=["session_type", "status"],
                        name="time_tracke_session_614a4e_idx",
                    ),
                    models.Index(
                        fields=["staff", "date"], name="time_tracke_staff_i_5939b3_idx"
                    ),
                    models.Index(
                        fields=["parent", "date"], name="time_tracke_parent__f57c0d_idx"
                    ),
                ],
            },
        ),
    ]
