# Generated by Django 5.0 on 2026-02-07 01:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("total_doses", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="additional_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="custom_student_id",
            field=models.CharField(
                blank=True, help_text="Custom student ID", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="desired_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="doctor_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="doctor_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="doctor_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HISPANIC", "Hispanic, Latino or Spanish Origin"),
                    ("NOT_HISPANIC", "Not of Hispanic, Latino or Spanish Origin"),
                    ("PREFER_NOT", "Prefer not to say"),
                ],
                default="PREFER_NOT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="expected_birth_date",
            field=models.DateField(
                blank=True, help_text="For unborn children", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="family_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="first_contact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="graduation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="has_subsidy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_SPECIFIED", "Not specified"),
                    ("BREAKFAST", "Breakfast"),
                    ("LUNCH", "Lunch"),
                    ("SNACK", "Snack"),
                    ("DINNER", "Dinner"),
                    ("ALL_MEALS", "All Meals"),
                ],
                default="NOT_SPECIFIED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="medications",
            field=models.TextField(blank=True, help_text="Current medications"),
        ),
        migrations.AddField(
            model_name="student",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="paperwork_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_employer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="programs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WHITE", "White"),
                    ("BLACK", "Black or African American"),
                    ("ASIAN", "Asian"),
                    ("NATIVE_AMERICAN", "American Indian or Alaska Native"),
                    ("PACIFIC_ISLANDER", "Native Hawaiian or Other Pacific Islander"),
                    ("TWO_OR_MORE", "Two or More Races"),
                    ("OTHER", "Other"),
                    ("PREFER_NOT", "Prefer not to say"),
                ],
                default="PREFER_NOT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="set_active_on_enrollment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="sibling_attending",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="subsidy_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="toured_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=200)),
                ("field_value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["field_name"],
            },
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_exempt",
                    models.BooleanField(
                        default=False, help_text="Student exempt from immunizations"
                    ),
                ),
                ("exemption_reason", models.TextField(blank=True)),
                ("on_catch_up_schedule", models.BooleanField(default=False)),
                ("catch_up_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="immunization_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunization_record",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Immunization Record",
                "verbose_name_plural": "Immunization Records",
            },
        ),
        migrations.CreateModel(
            name="StudentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        help_text="e.g., Mother, Father, Grandparent, Aunt, Authorized Pickup",
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=False, help_text="Authorized to pick up child"
                    ),
                ),
                ("is_emergency_contact", models.BooleanField(default=False)),
                (
                    "can_view_brightwheel",
                    models.BooleanField(
                        default=False, help_text="Can sign in to view child info"
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True, help_text="Code to add child in app", max_length=20
                    ),
                ),
                ("has_signed_up", models.BooleanField(default=False)),
                ("is_billing_contact", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="students.student",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="VaccineDoseSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose_number", models.PositiveIntegerField()),
                (
                    "recommended_age_months",
                    models.PositiveIntegerField(help_text="Recommended age in months"),
                ),
                (
                    "min_age_months",
                    models.PositiveIntegerField(
                        blank=True, help_text="Minimum age for this dose", null=True
                    ),
                ),
                (
                    "max_age_months",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum age for this dose", null=True
                    ),
                ),
                (
                    "cdc_recommendation_text",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2 mos', '12-15 mos', '4-6 yrs'",
                        max_length=200,
                    ),
                ),
                ("is_catch_up", models.BooleanField(default=False)),
                (
                    "vaccine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_schedules",
                        to="students.vaccinetype",
                    ),
                ),
            ],
            options={
                "ordering": ["vaccine_type", "dose_number"],
                "unique_together": {("vaccine_type", "dose_number")},
            },
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(default=datetime.date.today)),
                (
                    "report_number",
                    models.PositiveIntegerField(
                        help_text="Incident Report #1, #2, etc."
                    ),
                ),
                ("description", models.TextField()),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "report_number"],
                "unique_together": {("student", "report_number")},
            },
        ),
        migrations.CreateModel(
            name="VaccineDose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_administered",
                    models.DateField(
                        blank=True, help_text="Date this dose was given", null=True
                    ),
                ),
                (
                    "administered_by",
                    models.CharField(
                        blank=True,
                        help_text="Healthcare provider who administered",
                        max_length=200,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Clinic/hospital where administered",
                        max_length=200,
                    ),
                ),
                ("lot_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "immunization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccine_doses",
                        to="students.immunization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccine_doses_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dose_schedule",
                    models.ForeignKey(
                        help_text="CDC recommended schedule for this dose",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.vaccinedoseschedule",
                    ),
                ),
                (
                    "vaccine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.vaccinetype",
                    ),
                ),
            ],
            options={
                "ordering": ["vaccine_type", "dose_schedule__dose_number"],
                "unique_together": {("immunization", "vaccine_type", "dose_schedule")},
            },
        ),
    ]
